config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  root 'welcome#index'
  resources :decks do
      get "start"
      resources :cards
  end
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :deck
  validates :front, presence:true, length:{minimum:2}
  validates :verse, presence:true, length:{minimum:2}
  validates :deck, :uniqueness => {:scope => :front, message: "Already a similar card in deck"}
end

app/models/deck.rb
class Deck < ApplicationRecord
  belongs_to :user
  has_many :cards, dependent: :destroy
  validates :name, presence: true, length: {minimum: 5}
  validates_uniqueness_of :name, :scope =>[:user_id]

  def ozniak
    list = Array.new
    cards.shuffle.each do |card|
      e_factor = card[:e_factor]
      n_days = card[:n_days]
      date = card[:played_at]
      if (n_days == 0)
        pn = 0
      elsif (n_days == 1)
        pn = 1
      else
        pn = 7 + e_factor ** (n_days - 2)
      end
      if(date.nil?)
        list << card
      else
        if ((date.beginning_of_day + 86400 * pn.round).to_date <= Time.now.beginning_of_day.to_date || pn == 0)
          list << card
        end
      end
    end
    return list[0]
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :decks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  def after_sign_in_path_for(resource)
      decks_path
  end
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
    def new
        @deck = Deck.find(params[:deck_id])
        @card = Card.new
    end

    def edit
        @deck = Deck.find(params[:deck_id])
        @card = @deck.cards.find(params[:id])
    end

    def create
        @deck = Deck.find(params[:deck_id])
        @card = @deck.cards.create(card_params)
        if @deck.save
            redirect_to @deck 
        else
            render 'new' 
        end
    end
    def update
        @deck = Deck.find(params[:deck_id])
        @card = @deck.cards.find(params[:id])
        if @card.update(card_params)
            redirect_to @deck
        else
            render 'edit'
        end
    end

    def destroy
        @deck = Deck.find(params[:deck_id])
        @card = @deck.cards.find(params[:id])
        @card.destroy
        redirect_to @deck
    end

    def show
        @deck = Deck.find(params[:deck_id])
        @card = @deck.cards.find(params[:id])
    end
    def index
        redirect_to deck_path(params[:deck_id])
    end
    private
    def card_params
        params.require(:card).permit(:front, :verse, :time_to_appear)
    end
end

app/controllers/decks_controller.rb
class DecksController < ApplicationController
    before_action :authenticate_user!
    def new
        @deck=Deck.new
    end
    def edit
        @deck = current_user.decks.find(params[:id])
    end
    def create
        @deck = current_user.decks.create(deck_params)
        if @deck.save
            redirect_to @deck 
        else
            render 'new' 
        end
    end

    def update 
        @deck = current_user.decks.find(params[:id])
        if @deck.update(deck_params)
            redirect_to @deck
        else
            render 'edit'
        end
    end

    def destroy
        @deck = Deck.find(params[:id])
        @deck.destroy
        redirect_to decks_path
    end

    def show
        @deck = Deck.find(params[:id])
    end
    
    def index
        @deck = current_user.decks.all  
    end

    def start
        if (params[:card_id] == nil)
            params[:card_id] = 0
        end

        @deck = Deck.find(params[:deck_id])

        if (params[:grade] != nil)
            card = @deck.cards.find_by_id(params[:card_id])
            q = params[:grade].to_i
            
            if (params[:grade].to_i == 0)
                n_days = 0
                ef = card[:e_factor]
            else
                n_days = card[:n_days] + 1
                ef = card[:e_factor] + (0.1 - (3 - q) * (0.08 + (5 - q) * 0.02))
            end
            Card.where("deck_id = #{params[:deck_id]} AND id = #{params[:card_id]}").update_all("e_factor = #{ef}, played_at = '#{Time.now.strftime("%Y-%m-%d %H:%M:%S")}', n_days = #{n_days}")
        end

        @card = @deck.ozniak()
    end

    private
    def deck_params
        params.require(:deck).permit(:name, :description, :shareable)
    end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    if user_signed_in?
        redirect_to decks_path 
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/decks_helper.rb
module DecksHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/cards/_form.html.haml
= form_with model: [@deck, @card], local: true do |form| 
  - if @card.errors.any? 
    %div{:id=>"error_explanation"}
      %h2
        = pluralize(@card.errors.count, "error") 
        prohibited this article from being saved:
      %ul
        - @card.errors.full_messages.each do |msg| 
          %li= msg 
  %p
    = form.label :front 
    %br
    = form.text_field :front 
  %p
    = form.label :back 
    %br
    = form.text_field :verse 
  %p
    = form.submit

app/views/cards/edit.html.haml
%h1 Edit Card
= render 'form' 
= link_to 'Back', deck_path(@deck.id)

app/views/cards/new.html.haml
%h1 New card
= render 'form' 
= link_to 'Back', deck_path(@deck.id) 

app/views/cards/show.html.haml
%p
  =link_to 'Home', decks_path
  =link_to 'Back', deck_path(@deck.id)
%p
  %strong Name:
  = @card.front 
%p
  %strong Rear:
  = @card.verse
%p
  =link_to 'edit', edit_deck_card_path(@deck.id,@card.id)
  =link_to 'remove', deck_card_path(@deck.id,@card.id),method: :delete, data:{confirm: 'Are you sure?'}

app/views/decks/_form.html.haml
= form_with model: @deck, local: true do |form| 
  - if @deck.errors.any? 
    %div{:id=>"error_explanation"}
      %h2
        = pluralize(@deck.errors.count, "error") 
        prohibited this article from being saved:
      %ul
        - @deck.errors.full_messages.each do |msg| 
          %li= msg 
  %p{:class=>"form-group"}
    = form.label :name 
    %br
    = form.text_field :name  
  %p{:class=>"form-group"}
    = form.label :description 
    %br
    = form.text_area :description
    %br
  %p
    = form.check_box :shareable, :class => "checkbox"
    Public
    %br
  %p
    =form.submit :class=>["btn","btn-default"]  
    %br

app/views/decks/edit.html.haml
%h1 Edit Deck 
=render 'form' 
= link_to 'Back', decks_path 

app/views/decks/edit_1.html.haml
%h1 Edit article
=render 'form' 
= link_to 'Back', decks_path 

app/views/decks/index.html.haml
%div{:class=>"centro"}  
  %div{:class=>"myDecks"}
    %div{:class=>"jumbotron"}
      %h1 My Decks
      %div{:class=>"card-list"}
      - for deck in @deck
        %li
          =link_to deck.name, deck_path(deck.id)
          =link_to 'edit', edit_deck_path(deck.id)
          =link_to 'remove', deck_path(deck.id),method: :delete, data:{confirm: 'Are you sure?'}
      %p{:class=>"bottom-right"}= link_to 'New deck', new_deck_path
  %div{:class=>"allDecks"}
    %div{:class=>"jumbotron"}
      %h1 Popular Decks 
      %div{:class=>"card-list"}
        - for deck in Deck.where("shareable = 't'").all 
          %li
            =link_to deck.name + " (User: #{User.where("id = " + deck.user_id.to_s).all[0].email})" , deck_path(deck.id)

app/views/decks/new.html.haml
%h1 New Deck
= render 'form' 
= link_to 'Back', decks_path 

app/views/decks/show.html.haml
%p=link_to 'Home', decks_path
%div{:class=>"left"}
  %div{:class=>"jumbotron"}
    %h1= @deck.name 
    %p
      %strong Number of Cards:
      = @deck.cards.count
    %p
      = @deck.description
    =link_to 'start', deck_start_path(@deck.id) ,:class=>"btn btn-default"   
%div{:class=>"right"}
  %div{:class=> "jumbotron"}
    %p
      %strong Card list
      -@deck.cards.sort_by{|o| o.front}.each do |card| 
        %li
          =card.front
          =link_to 'edit', edit_deck_card_path(@deck.id,card.id)
          =link_to 'remove', deck_card_path(@deck.id,card.id),method: :delete, data:{confirm: 'Are you sure?'}
    %p{:class=>"bottom-right"}=link_to 'New Card', new_deck_card_path(@deck.id)

app/views/decks/start.html.haml
%div
  =link_to 'Home', decks_path
  =link_to 'Back', deck_path(@deck.id)
%h1
  %div{:class=>"start"}
    %div{:class=>"jumbotron"}
      %h1
        %div{:class=>"upper"}=@deck.name
        - if @card == nil
          %div{:class=>"card"} 
            No more cards to study today
        - else
 
          %div{:class=>"card", :onclick=>"turn(this)"}
            %div{:class=>"card-face card-face-front"}
              =@card.front
            %div{:class=>"card-face card-face-back"}
              =@card.verse
          %div  
            =link_to 'Wrong', deck_start_path({:deck_id => @deck.id,  :card_id => @card.id, :grade => 0}),:class=>"btn btn-default"
            =link_to 'Regular', deck_start_path({:deck_id => @deck.id, :card_id => @card.id, :grade => 1}), :class=>"btn btn-default"
            =link_to 'Good', deck_start_path({:deck_id => @deck.id, :card_id => @card.id, :grade => 2}), :class=>"btn btn-default"

app/views/layouts/_footer.html.haml
%footer{:class => "footer"}
  %div{:clas=>"container"}
    %small
      Wanki - The Anki application for Web
    %nav
      %ul
        %li= link_to "About",   '#' 
        %li= link_to "Contact", '#' 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Wanki</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <% if user_signed_in? %>
      <li>
              <%= current_user.email %>   
              <%= link_to('Logout', destroy_user_session_path, method: :delete) %>        
        </li>
  <% else %>
      <li>
            <%= link_to('Login', new_user_session_path)  %>  
            <%= link_to('Register', new_user_registration_path)  %>  
        </li>
  <% end %>
  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/application.html.haml
!!!
%html
  %head
    / %meta{:content => ["text/html", "charset=UTF-8"], "http-equiv" => "Content-Type"}
    %title Wanki - the Anki app for Web
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    %header{:class=>["navbar"," navbar-fixed-top", "navbar-inverse"]}
      %div{:class=>"container"}
        =link_to "Wanki", welcome_index_path, id:"logo"
        %nav
          %ul{:class=>["nav"," navbar-nav"," navbar-right"]}         
            - if user_signed_in?
              %li= link_to current_user.email, welcome_index_path
              %li= link_to 'Logout', destroy_user_session_path, method: :delete
            - else 
              %li= link_to('Login', new_user_session_path)    
              %li= link_to('Register', new_user_registration_path) 
    %div{:class=>"container"}        
      = yield
      = render 'layouts/footer'

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/users/shared/_links.html.haml
- if controller_name != 'sessions'
  = link_to "Log in", new_session_path(resource_name)
  %br/
- if devise_mapping.registerable? && controller_name != 'registrations'
  = link_to "Sign up", new_registration_path(resource_name)
  %br/
- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations'
  = link_to "Forgot your password?", new_password_path(resource_name)
  %br/
- if devise_mapping.confirmable? && controller_name != 'confirmations'
  = link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name)
  %br/
- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks'
  = link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name)
  %br/
- if devise_mapping.omniauthable?
  - resource_class.omniauth_providers.each do |provider|
    = link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider)
    %br/

app/views/welcome/index.html.haml
%div{ :class=>"center jumbotron"}
  %h1 Welcome to Wanki! 
  %p Wanki is a Anki like web application that helps you memorize things using flashcards. 